name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build iT -i --stacktrace
      - name: Coverage
        run: ./gradlew jacocoTestReport coveralls -i --stacktrace
      - name: Publish test results
        uses: dorny/test-reporter@v1
        with:
          name: Unit Tests
          path: build/test-results/**/TEST-*.xml
          reporter: junit
          check_name: Tests Results
  build-java-17:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew integrationTest --tests JcstressPluginJava17Spec -i --stacktrace
      - name: Publish test results
        uses: dorny/test-reporter@v1
        with:
          name: Unit Tests
          path: build/test-results/**/TEST-*.xml
          reporter: junit
          check_name: Tests Results
